steps:
  # 1. Build the application image, which is now very fast because it uses the base image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '.'

  # 2. Push the lightweight application image to Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

  # 3. Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Fail on any error
      set -e

      # Define environment-specific variables
      MIN_INSTANCES="0"
      APP_ENV="local"
      AUTH_SETTINGS="--allow-unauthenticated"
      
      # Production settings for the 'main' branch
      if [ "$BRANCH_NAME" == "main" ]; then
        echo "Branch is 'main'. Applying production settings."
        MIN_INSTANCES="1"
        APP_ENV="production"
        # Secure the endpoint by removing public access and specifying the invoker
        AUTH_SETTINGS="--no-allow-unauthenticated --invoker=service-account:vercel-backend-sa@data-pipelines-450611.iam.gserviceaccount.com"
      else
        echo "Branch is not 'main'. Applying development settings."
      fi

      # Execute the deployment command with the correct settings
      gcloud run deploy '${_SERVICE_NAME}' \
        --image='${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}' \
        --region='${_LOCATION}' \
        --platform=managed \
        --memory=16Gi \
        --cpu=4 \
        --min-instances=${MIN_INSTANCES} \
        --cpu-boost \
        --timeout=600 \
        --concurrency=1 \
        --set-env-vars="APP_ENV=${APP_ENV},ALLOWED_CALLER_EMAIL=vercel-backend-sa@data-pipelines-450611.iam.gserviceaccount.com" \
        ${AUTH_SETTINGS}

# Store the final application image in Artifact Registry.
images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

# Define your substitution variables.
substitutions:
  _SERVICE_NAME: 'qwen-embedding-api'
  _REPO_NAME: 'embedding-services' # Must match the name of your Artifact Registry repo
  _LOCATION: 'us-central1'         # Should match the region of your Artifact Registry repo

# Specify the logging option. A powerful machine type is no longer needed here.
options:
  logging: CLOUD_LOGGING_ONLY